# Generated by Django 4.0.4 on 2022-08-11 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0002_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='vaqt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
